services:
  hf-executor:
    image: kuwaai/model-executor
    environment:
      EXECUTOR_TYPE: huggingface
      EXECUTOR_ACCESS_CODE: gemma-7b-it
      EXECUTOR_NAME: Google Gemma 7B Instruct
      EXECUTOR_IMAGE: huggingface.svg # Refer to src/multi-chat/public/images
      HUGGING_FACE_HUB_TOKEN: ${HUGGING_FACE_HUB_TOKEN}
      TRANSFORMERS_OFFLINE: ${TRANSFORMERS_OFFLINE:-0}
    depends_on:
      - executor-builder
      - kernel
      - multi-chat
    command: ["--model_path", "google/gemma-7b-it", "--no_system_prompt"]
    restart: unless-stopped
    volumes: ["~/.cache/huggingface:/root/.cache/huggingface"]
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            device_ids: ['0']
            capabilities: [gpu]
    networks: ["backend"]