services:
  pipe-executor:
    build:
      context: ../../
      dockerfile: docker/executor/Dockerfile
    image: kuwa-executor
    environment:
      CUSTOM_EXECUTOR_PATH: ./pipe/main.py
      EXECUTOR_ACCESS_CODE: pipe
      EXECUTOR_NAME: Pipe
      EXECUTOR_IMAGE: pipe.png # Refer to src/multi-chat/public/images
    depends_on:
      - kernel
      - multi-chat
    command: [
      "--api_base_url", "http://web/",
      "--log", "debug"
    ]
    volumes: [
      "kuwa-root:/var/kuwa/docker/root:rw", # The root of Kuwa filesystem hierarchy to store user-uploaded data during runtime.
    ]
    extra_hosts:
      - "localhost:host-gateway"
    restart: unless-stopped
    networks: ["backend", "frontend"]