services:
  pipe-executor:
    build:
      context: ../../
      dockerfile: docker/executor/Dockerfile
    image: kuwa-executor
    environment:
      CUSTOM_EXECUTOR_PATH: ./pipe/main.py
      EXECUTOR_ACCESS_CODE: pipe
      EXECUTOR_NAME: Pipe
      EXECUTOR_IMAGE: pipe.png # Refer to src/multi-chat/public/images
    depends_on:
      - kernel
      - multi-chat
    command: [
      "--path", "/var/kuwa/bin",
      "--log", "debug"
    ]
    volumes: [
      "../root:/var/kuwa:rw", # The root of Kuwa filesystem hierarchy to store user-uploaded data during runtime.
    ]
    restart: unless-stopped
    networks: ["backend", "frontend"]