services:
  sysinfo-executor:
    image: kuwaai/model-executor
    environment:
      EXECUTOR_TYPE: sysinfo
      EXECUTOR_ACCESS_CODE: tool/sysinfo
      EXECUTOR_NAME: System Info
      EXECUTOR_IMAGE: info.png # Refer to src/multi-chat/public/images
    depends_on:
      - executor-builder
      - kernel
    command: ['--log', 'debug']
    restart: unless-stopped
    networks: ["backend"]
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #       - driver: nvidia
    #         device_ids: ['0']
    #         capabilities: [gpu]