services:
  token-counter-executor:
    image: kuwaai/model-executor
    environment:
      CUSTOM_EXECUTOR_PATH: ./token_counter/main.py
      EXECUTOR_ACCESS_CODE: tool/token_counter
      EXECUTOR_NAME: Token Counter
      EXECUTOR_IMAGE: counter.png # Refer to src/multi-chat/public/images
    depends_on:
      - executor-builder
      - kernel
      - multi-chat
    command: []
    restart: unless-stopped
    networks: ["backend"]